Replace the Visit Site image path
pantheon-systems/terminus-build-tools-plugin pull request #343
Opened 2020-05-01 20:26 UTC by sugaroverflow

Solves #281 to update the Visit Site path with the tagged release path instead of master in case we change it in the future.

2020-05-04 14:12 UTC, rvtraveller requested changes
I think we need to include `?raw=true` at the end of our URLs so we get the raw image.

2020-05-04 19:14 UTC, sugaroverflow commented
Gotcha, changes made.

2021-06-08 17:59 UTC, greg-1-anderson approved these changes

2021-06-08 18:39 UTC, rvtraveller approved these changes
LGTM!

2025-02-21 23:33 UTC, closed without merging