Add composer repository option to project create command.
pantheon-systems/terminus-build-tools-plugin pull request #390
Opened 2021-07-15 01:47 UTC by kporras07

To use a private repository, define the auth string like this:

```
export TERMINUS_BUILD_TOOLS_COMPOSER_AUTH=json_encoded_string
```

or in .terminus/config.yml as described at https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/main/src/Utility/Config.php#L21

Then, in the build:project:create command, pass a composer-repository option like this:

```
terminus build:project:create --composer-repository="https://repo.packagist.com/kporras07" kporras07/example-drops-8-test my-project
```

2021-07-15 02:33 UTC, greg-1-anderson requested changes
This looks great. Could you also update the README with info from the instructions you included in this PR's conversation, and also a link to external documentation on setting up a packagist repo?

2021-07-15 23:22 UTC, greg-1-anderson commented
One more request: let's give folks a hint on where to find info on the authentication information. Maybe the best docs link would be: https://getcomposer.org/doc/articles/authentication-for-private-packages.md#authentication-in-auth-json-per-project

Feel free to substitute something else if there's a different location you think is more relevant.

2021-07-15 23:49 UTC, kporras07 commented
@greg-1-anderson thanks. Done.

2021-07-15 23:59 UTC, greg-1-anderson approved these changes
Looks good to merge once tests pass.

2021-07-16 01:10 UTC, kporras07 commented
@greg-1-anderson I updated the PR to include CMS-146

2021-07-16 14:10 UTC, greg-1-anderson commented
I was wondering if we could save the user from the need to specify the project name, i.e. instead of:
```
terminus build:project:create --template-repository="git@github.com:kporras07/myrepo.git" kporras07/myrepo-template my-project
```
How about:
```
terminus build:project:create git@github.com:kporras07/myrepo.git my-project
```
If build:project:create detects that the template parameter is a git URL instead of org/project, then use it to set the template repository and read the composer.json to get the project name. This will involve some redundant project access (once by us and once by Composer), but a clone with depth 0 shouldn't take very long.

This could perhaps be in addition to the current implementation, so that folks have the option of typing everything out if they want to avoid the extra download (on a slow connection or whatever).

What do you think about that?

2021-07-16 14:30 UTC, kporras07 commented
Sounds good. I'll look into this.

And what if it's a private composer repository?  How should the command look?

2021-07-16 15:38 UTC, greg-1-anderson commented
The private composer repository will need both parameters, i.e. unchanged from the current implementation in this PR.

2021-07-17 01:12 UTC, kporras07 commented
@greg-1-anderson updated. Please take another look.

2021-07-20 19:18 UTC, greg-1-anderson commented on src/Commands/BuildToolsBase.php
> +            if (preg_match('/"name":\s"([A-Za-z0-9\-]+\/[A-Za-z0-9\-]+)"/', $composer_json_contents, $matches)) {
Please use json_decode here instead of a regex match.

2021-07-20 19:19 UTC, greg-1-anderson commented
@kporras07 I invited you to this repo; could you please re-submit this PR from a branch in this repository so that the tests can run. With the json_decode change and passing tests, I think this will be ready to go.

2021-07-21 00:44 UTC, kporras07 commented
Closing in favor of #391

2021-07-21 00:44 UTC, closed without merging